### ISSUE TITLE
initial release install error

### ISSUE THREAD

**Issue by DavidFW1960** [kanine/bomWeather-2020#1] opened 2020-10-07 02:29 UTC
Error:

Invalid package:
bomWeather-2020-0.1.rmskin

The Skin Packager tool must be used to create valid .rmskin packages

This is generally build within rainmeter..

**Comment by kanine** [comment] 2020-10-07 03:25
Suspect this is something missing in the zip file that githubs creating, I'll check it out.

**Comment by kanine** [comment] 2020-10-08 03:27
> (As of version 2.3, Rainmeter will not install a normal ZIP file changed to the ".rmskin" extension; the package must be created with the Skin Packager.)

Looks like I'll have to make one as part of the distribution, otherwise change the install instructions which is frankly a little easier on maintenance.

**Comment by DavidFW1960** [comment] 2020-10-08 03:33
Ah makes sense.
The ABB one I maintain I don't do releases at all I just upload the .rmskin file and people download that.

**Comment by kanine** [comment] 2020-10-08 03:36
I've updated the installation instructions for now but will leave this open as a reminder. If I can script the generation I'll incorporate a distribution of a .rmskin in the future.

**Comment by kanine** [comment] 2020-10-26 07:33
Unfortunately I've not been able to reproduce this. Closing for now.

**Closed as completed by kanine** 2020-10-26 07:33 UTC
